import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import 'react-image-crop/dist/ReactCrop.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'House of Gaia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-gray-800`}>
        <main>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}
